#!/usr/bin/perl

use strict;
use warnings;

use File::Basename;
use File::Path qw(make_path);
use Pod::Markdown;
use Git::Repository;
use File::Basename;

my $tmpDir = "/home/goneri/fusioninventory/tmp/wikigit";

my @repoList = (
    {

        name => 'agent',
        url =>
          'git+ssh://forge.fusioninventory.org/git/fusioninventory/agent.git',
        branches => [
            {
                'serie'  => '2.3.x',
                'branch' => 'master',
                'status' => 'dev'
            },
        ]
    }
);


my $indexContent = "# Reference documentation\n";

my $wiki = Git::Repository->new( work_tree => '.' );
#eval { $wiki->run('rm', '-rf', "documentation/references") };
foreach my $repo (@repoList) {
    use Data::Dumper;
    my $localDir = sprintf( "%s/%s", $tmpDir, $repo->{name} );

    if ( !-d $localDir && !make_path($localDir) ) {
        die "mkdir failed\n";
    }

    if ( !-d "$localDir/.git" ) {
        Git::Repository->run( 'clone' => $repo->{url}, $localDir );
    }
    my $r = Git::Repository->new( work_tree => $localDir );
    $r->run( 'fetch', 'origin' );

    foreach my $fullpath ( glob("$localDir/bin/fusioninventory-*") ) {
        my $filename = basename($fullpath);

        $indexContent .= "\n## $filename\n\n" unless $filename =~ /pm$/;

        foreach my $branch ( @{ $repo->{branches} } ) {

            my $content =
              eval{ $r->run( 'show', 'origin/' . $branch->{branch} . ':' . 'bin/' . $filename ) };


            open TMP, ">$localDir/tmpfile" or die;
            print TMP $content;
            close TMP;

            my $mdwnFile = sprintf("documentation/references/%s/%s/%s", $repo->{name}, $branch->{serie}, $filename);
            print $mdwnFile. "\n";

            next unless $content;

            my $parser = Pod::Markdown->new;
            $parser->parse_from_file("$localDir/tmpfile");
            make_path( dirname( $mdwnFile . '.mdwn' ) );
            open OUT, ">" . $mdwnFile . '.mdwn' or die "$!";

            if ($branch->{status} !~ /stable/) {
                print OUT '[[!template  id=warning text="The '.$branch->{serie}.' serie is still in developpement."]]'."\n\n";
            } elsif ($branch->{status} eq 'oldstable') {
                print OUT '[[!template  id=info text="The '.$branch->{serie}.' is not maintained anymore. You should consider an upgrade to the last stable release."]]'."\n\n";
            }
            print OUT $parser->as_markdown;
            close OUT;
            $wiki->run('add', $mdwnFile . '.mdwn');
            $indexContent .= "* [[".$branch->{serie}." (".$branch->{status}.")|$mdwnFile]]\n" unless $filename =~ /pm$/;

        }

    }

}

open INDEX, ">documentation/references.mdwn" or die;
print INDEX $indexContent;
close INDEX;
$wiki->run('add', "documentation/references.mdwn");

