#!/usr/bin/perl

use strict;
use warnings;

use File::Basename;
use File::Path qw(make_path);
use Pod::Markdown;
use Git::Repository;
use File::Basename;

my $tmpDir = "/home/goneri/fusioninventory/tmp/wikigit";

my @repoList = (
    {

        name => 'agent',
        url =>
        'git+ssh://forge.fusioninventory.org/git/fusioninventory/agent.git',
        branches => [
            {
                'serie'  => '2.3.x',
                'branch' => '2.3.x',
                'status' => 'stable'
            },
        ]
    },
    {

        name => 'agent',
        url =>
        'git+ssh://forge.fusioninventory.org/git/fusioninventory/agent.git',
        branches => [
            {
                'serie'  => '2.2.x',
                'branch' => '2.2.x',
                'status' => 'stable'
            },
        ]
    },
    {

        name => 'agent',
        url =>
        'git+ssh://forge.fusioninventory.org/git/fusioninventory/agent.git',
        branches => [
            {
                'serie'  => '2.1.x',
                'branch' => '2.1.x',
                'status' => 'oldstable'
            },
        ]
    }

);


my $indexContent = "# Reference documentation\n";

my $wiki = Git::Repository->new( work_tree => '.' );
foreach my $repo (@repoList) {
    use Data::Dumper;
    my $localDir = sprintf( "%s/%s", $tmpDir, $repo->{name} );

    if ( !-d $localDir && !make_path($localDir) ) {
        die "mkdir failed\n";
    }

    if ( !-d "$localDir/.git" ) {
        Git::Repository->run( 'clone' => $repo->{url}, $localDir );
    }
    my $r = Git::Repository->new( work_tree => $localDir );
    $r->run( 'fetch', 'origin' );
    foreach my $branch ( @{ $repo->{branches} } ) {
        $r->run( 'checkout', 'origin/'.$branch->{branch} );


        foreach my $fullpath ( glob("$localDir/bin/fusioninventory-*"), glob("$localDir/fusioninventory-*") ) {
            my $filename = basename($fullpath);
            print $fullpath."\n";

            $indexContent .= "\n## $filename\n\n" unless $filename =~ /pm$/;


            my $mdwnFile = sprintf("documentation/references/%s/%s/%s", $repo->{name}, $branch->{serie}, $filename);
            print $mdwnFile. "\n";

            my $parser = Pod::Markdown->new;
            $parser->parse_from_file($fullpath);
            make_path( dirname( $mdwnFile . '.mdwn' ) );
            open OUT, ">" . $mdwnFile . '.mdwn' or die "$!";

            if ($branch->{status} !~ /stable/) {
                print OUT '[[!template  id=warning text="The '.$branch->{serie}.' serie is still in developpement."]]'."\n\n";
            } elsif ($branch->{status} eq 'oldstable') {
                print OUT '[[!template  id=info text="The '.$branch->{serie}.' is not maintained anymore. You should consider an upgrade to the last stable release."]]'."\n\n";
            }
            print OUT $parser->as_markdown;
            close OUT;
            $wiki->run('add', $mdwnFile . '.mdwn');
            $indexContent .= "* [[".$branch->{serie}." (".$branch->{status}.")|$mdwnFile]]\n" unless $filename =~ /pm$/;

        }

    }

}

open INDEX, ">documentation/references.mdwn" or die;
print INDEX $indexContent;
close INDEX;
$wiki->run('add', "documentation/references.mdwn");

