name: Build the website
on:
  pull_request:
      branches: [ master ]

jobs:
  build:
    name: Build the website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: install bundle
        run: sudo gem install bundler
      - name: install dep gem
        run: sudo bundle install
      - name: build
        run: bundle exec jekyll build
